apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-mgqx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-mgqx
    app.kubernetes.io/part-of: integ-app-jnez
  name: hacbs-test-project-mgqx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-mgqx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-mgqx
    spec:
      containers:
      - image: quay.io/quay-or-not-to-quay/nbe-e2e-iiiv-tenant/integ-app-jnez/hacbs-test-project-mgqx@sha256:4f3a50c404caa6c8a85f82163fde97934ce28c821b83d0f282904d3a4930a8de
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
